# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    # Turn off studio-rpc-usb-uart for now
    # snippet: zmk-usb-logging
    # geeksville: turn off studio for now -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    # cmake-args:  -DCONFIG_ZMK_LOG_LEVEL=4
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    #snippet: zmk-usb-logging
    #cmake-args: -DCONFIG_INPUT_LOG_LEVEL_DBG=y
  - board: seeeduino_xiao_ble
    shield: settings_reset

